select PRODUCTSTABLE.PRODUCTNAME, CATEGORYTABLE.CATEGORYNAME
from PRODUCTSTABLE, CATEGORYTABLE
where CATEGORYTABLE.PRODUCTID = PRODUCTSTABLE.ID
union
select PRODUCTSTABLE.PRODUCTNAME, 'без категории' as CATEGORYNAME
from PRODUCTSTABLE
where PRODUCTSTABLE.ID not in (select CATEGORYTABLE.PRODUCTID from CATEGORYTABLE)     